name: Run Python Script

on:
  schedule:
    - cron: '0 * * * *' # At 00:00 on Monday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v2
        # Check out the repository content to GitHub runner

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          # Install the Python version needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Upgrade pip and install dependencies from requirements.txt

      - name: Run Python script and log errors
        run: |
          python main.py > output.log 2>&1
          if grep -q "Error" output.log; then
            echo "Errors found in script execution. Check the log for details."
            exit 1
          fi
        # Run the Python script and redirect output to a log file

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "Updated logs" --allow-empty)
          # Commit changes if there are any

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          # Push changes to the specified branch
